# Macro file for the initialization of example B2
# in interactive session
#
# Set some default verbose
#/control/verbose 2
#/control/saveHistory
/tracking/verbose 1
#/run/verbose 2

/detGeometry/DebugMode false
/detGeometry/OverlapCheck false

####################
## Select Detector
####################
/detector/select AmoreDetector
/detGeometry/select amore200 #amore200, amoreI, amorepilot, mydetector

#############################
## Select Detector Geometry
#############################
# AMoRE-II detector option
/detGeometry/200/selectPhase AMoRE200_Phase1 #AMoRE200_Phase1, AMoRE200_Phase2
/detGeometry/200/selectSimType RealMode #RackGammaMode, NeutronMode, IdealMode, RealMode
/detGeometry/200/selectNSDesign Design5 #Design1, Design2, Design3, Design4, Design5
/detGeometry/AdditionalPE true

# AMoRE-I option
/detGeometry/I/EnableSuperCMagneticShield true
/detGeometry/I/EnableCrystalArray true

# AMoRE-Pilot option
/detGeometry/Pilot/EnableMumetal false
/detGeometry/Pilot/EnableTargetRoom true

/detGeometry/EnableOrigGeom true
/detGeometry/EnableScint true
/detGeometry/EnableGantry true
/detGeometry/EnableInnerDet true
/detGeometry/EnableInnermost true
/detGeometry/EnableNeutronShield true
/detGeometry/NeutronMode false
/detGeometry/nShieldingToyConf PE20cm

/ntuple/recordWithCut false

# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize

/event/output_file vis_output

#
# Visualization setting
/control/execute vis.mac
